# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

# !!! autogenerated code, do not change manually !!!
# generated on 2026-09-10 09:07:06.625370+02:00

"""Node identifiers from the OPC UA 'Di' nodeset. Auto-generated."""

from typing import ClassVar, final

from asyncua import ua
from opensmi.core.frozen import FrozenMeta
from opensmi.core.ua import NodeIdDefinition


@final
class DiNodeIds(metaclass=FrozenMeta):
    """Node identifiers from the OPC UA 'Di' nodeset. Auto-generated."""

    FILE_NAME: ClassVar[str] = "Opc.Ua.Di.NodeSet2.xml"
    URI: ClassVar[str] = "http://opcfoundation.org/UA/DI/"
    VERSION: ClassVar[str] = "1.04.0"
    REQUIRED_URIS: ClassVar[tuple[str, ...]] = ()

    BaseLifetimeIndicationType = NodeIdDefinition(URI, ua.Int32(473))
    BlockType = NodeIdDefinition(URI, ua.Int32(1003))
    CachedLoadingType = NodeIdDefinition(URI, ua.Int32(171))
    CheckFunctionAlarmType = NodeIdDefinition(URI, ua.Int32(15441))
    ComponentType = NodeIdDefinition(URI, ua.Int32(15063))
    ConfigurableObjectType = NodeIdDefinition(URI, ua.Int32(1004))
    ConfirmationStateMachineType = NodeIdDefinition(URI, ua.Int32(307))
    ConnectionPointType = NodeIdDefinition(URI, ua.Int32(6308))
    DeviceHealthDiagnosticAlarmType = NodeIdDefinition(URI, ua.Int32(15143))
    DeviceHealthEnumeration = NodeIdDefinition(URI, ua.Int32(6244))
    DeviceType = NodeIdDefinition(URI, ua.Int32(1002))
    DiameterIndicationType = NodeIdDefinition(URI, ua.Int32(478))
    DirectLoadingType = NodeIdDefinition(URI, ua.Int32(153))
    FailureAlarmType = NodeIdDefinition(URI, ua.Int32(15292))
    FetchResultDataType = NodeIdDefinition(URI, ua.Int32(6522))
    FileSystemLoadingType = NodeIdDefinition(URI, ua.Int32(192))
    FunctionalGroupType = NodeIdDefinition(URI, ua.Int32(1005))
    IDeviceHealthType = NodeIdDefinition(URI, ua.Int32(15051))
    IOperationCounterType = NodeIdDefinition(URI, ua.Int32(480))
    ISupportInfoType = NodeIdDefinition(URI, ua.Int32(15054))
    ITagNameplateType = NodeIdDefinition(URI, ua.Int32(15048))
    IVendorNameplateType = NodeIdDefinition(URI, ua.Int32(15035))
    InstallationStateMachineType = NodeIdDefinition(URI, ua.Int32(249))
    LengthIndicationType = NodeIdDefinition(URI, ua.Int32(477))
    LifetimeVariableType = NodeIdDefinition(URI, ua.Int32(468))
    LockingServicesType = NodeIdDefinition(URI, ua.Int32(6388))
    MaintenanceRequiredAlarmType = NodeIdDefinition(URI, ua.Int32(15739))
    NetworkType = NodeIdDefinition(URI, ua.Int32(6247))
    NumberOfPartsIndicationType = NodeIdDefinition(URI, ua.Int32(475))
    NumberOfUsagesIndicationType = NodeIdDefinition(URI, ua.Int32(476))
    OffSpecAlarmType = NodeIdDefinition(URI, ua.Int32(15590))
    PackageLoadingType = NodeIdDefinition(URI, ua.Int32(137))
    ParameterResultDataType = NodeIdDefinition(URI, ua.Int32(6525))
    PowerCycleStateMachineType = NodeIdDefinition(URI, ua.Int32(285))
    PrepareForUpdateStateMachineType = NodeIdDefinition(URI, ua.Int32(213))
    ProtocolType = NodeIdDefinition(URI, ua.Int32(1006))
    SoftwareLoadingType = NodeIdDefinition(URI, ua.Int32(135))
    SoftwareType = NodeIdDefinition(URI, ua.Int32(15106))
    SoftwareUpdateType = NodeIdDefinition(URI, ua.Int32(1))
    SoftwareVersionFileType = NodeIdDefinition(URI, ua.Int32(331))
    SoftwareVersionType = NodeIdDefinition(URI, ua.Int32(212))
    SubstanceVolumeIndicationType = NodeIdDefinition(URI, ua.Int32(479))
    TimeIndicationType = NodeIdDefinition(URI, ua.Int32(474))
    TopologyElementType = NodeIdDefinition(URI, ua.Int32(1001))
    TransferResultDataDataType = NodeIdDefinition(URI, ua.Int32(15889))
    TransferResultErrorDataType = NodeIdDefinition(URI, ua.Int32(15888))
    TransferServicesType = NodeIdDefinition(URI, ua.Int32(6526))
    UIElementType = NodeIdDefinition(URI, ua.Int32(6246))
    UpdateBehavior = NodeIdDefinition(URI, ua.Int32(333))
