# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

# !!! autogenerated code, do not change manually !!!
# generated on 2026-09-10 09:07:06.723837+02:00

"""Node identifiers from the OPC UA 'ECM' nodeset. Auto-generated."""

from typing import ClassVar, final

from asyncua import ua
from opensmi.core.frozen import FrozenMeta
from opensmi.core.ua import NodeIdDefinition


@final
class ECMNodeIds(metaclass=FrozenMeta):
    """Node identifiers from the OPC UA 'ECM' nodeset. Auto-generated."""

    FILE_NAME: ClassVar[str] = "Opc.Ua.ECM.NodeSet2.xml"
    URI: ClassVar[str] = "http://opcfoundation.org/UA/ECM/"
    VERSION: ClassVar[str] = "1.0.0"
    REQUIRED_URIS: ClassVar[tuple[str, ...]] = ("http://opcfoundation.org/UA/DI/", "http://opcfoundation.org/UA/IA/")

    AcPeDataType = NodeIdDefinition(URI, ua.Int32(3005))
    AcPpDataType = NodeIdDefinition(URI, ua.Int32(3006))
    AccuracyDomainType = NodeIdDefinition(URI, ua.Int32(1014))
    EnergyDevicePowerOffType = NodeIdDefinition(URI, ua.Int32(1012))
    EnergyMeasurementType = NodeIdDefinition(URI, ua.Int32(1006))
    EnergyMeasurementValueType = NodeIdDefinition(URI, ua.Int32(2002))
    EnergySavingModeStatusType = NodeIdDefinition(URI, ua.Int32(1002))
    EnergySavingModeType = NodeIdDefinition(URI, ua.Int32(1003))
    EnergySavingModesContainerType = NodeIdDefinition(URI, ua.Int32(1004))
    EnergyStandbyManagementType = NodeIdDefinition(URI, ua.Int32(1005))
    EnergyStateInformationDataType = NodeIdDefinition(URI, ua.Int32(3003))
    IEnergyProfileD0Type = NodeIdDefinition(URI, ua.Int32(1011))
    IEnergyProfileE0Type = NodeIdDefinition(URI, ua.Int32(1007))
    IEnergyProfileE1Type = NodeIdDefinition(URI, ua.Int32(1008))
    IEnergyProfileE2Type = NodeIdDefinition(URI, ua.Int32(1009))
    IEnergyProfileE3Type = NodeIdDefinition(URI, ua.Int32(1010))
    StandbyModeTransitionDataType = NodeIdDefinition(URI, ua.Int32(3002))
