# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

# !!! autogenerated code, do not change manually !!!
# generated on 2026-09-10 09:07:06.783804+02:00

"""Node identifiers from the OPC UA 'IA' nodeset. Auto-generated."""

from typing import ClassVar, final

from asyncua import ua
from opensmi.core.frozen import FrozenMeta
from opensmi.core.ua import NodeIdDefinition


@final
class IANodeIds(metaclass=FrozenMeta):
    """Node identifiers from the OPC UA 'IA' nodeset. Auto-generated."""

    FILE_NAME: ClassVar[str] = "Opc.Ua.IA.NodeSet2.xml"
    URI: ClassVar[str] = "http://opcfoundation.org/UA/IA/"
    VERSION: ClassVar[str] = "1.01.0"
    REQUIRED_URIS: ClassVar[tuple[str, ...]] = ("http://opcfoundation.org/UA/DI/",)

    AcousticSignalType = NodeIdDefinition(URI, ua.Int32(1009))
    BaseCalibrationTargetCategoryType = NodeIdDefinition(URI, ua.Int32(1014))
    BasicStacklightType = NodeIdDefinition(URI, ua.Int32(1002))
    CalibrationTargetType = NodeIdDefinition(URI, ua.Int32(1019))
    CalibrationValueType = NodeIdDefinition(URI, ua.Int32(2002))
    CapacityRangeType = NodeIdDefinition(URI, ua.Int32(2003))
    ControlChannelType = NodeIdDefinition(URI, ua.Int32(1008))
    DynamicCalibrationTargetCategoryType = NodeIdDefinition(URI, ua.Int32(1018))
    IAggregateStatisticsType = NodeIdDefinition(URI, ua.Int32(1012))
    IRollingStatisticsType = NodeIdDefinition(URI, ua.Int32(1013))
    IStatisticsType = NodeIdDefinition(URI, ua.Int32(1011))
    LevelDisplayMode = NodeIdDefinition(URI, ua.Int32(3003))
    OneTimeCalibrationTargetCategoryType = NodeIdDefinition(URI, ua.Int32(1017))
    ReusableCalibrationTargetCategoryType = NodeIdDefinition(URI, ua.Int32(1015))
    ReusableDeviceCalibrationTargetCategoryType = NodeIdDefinition(URI, ua.Int32(1016))
    SignalColor = NodeIdDefinition(URI, ua.Int32(3004))
    SignalModeLight = NodeIdDefinition(URI, ua.Int32(3005))
    StackElementAcousticType = NodeIdDefinition(URI, ua.Int32(1007))
    StackElementLightType = NodeIdDefinition(URI, ua.Int32(1006))
    StackElementType = NodeIdDefinition(URI, ua.Int32(1005))
    StackLevelType = NodeIdDefinition(URI, ua.Int32(1003))
    StackRunningType = NodeIdDefinition(URI, ua.Int32(1004))
    StacklightOperationMode = NodeIdDefinition(URI, ua.Int32(3002))
    StacklightType = NodeIdDefinition(URI, ua.Int32(1010))
