# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

# !!! autogenerated code, do not change manually !!!
# generated on 2026-09-10 09:07:06.850655+02:00

"""Node identifiers from the OPC UA 'LaserSystems' nodeset. Auto-generated."""

from typing import ClassVar, final

from asyncua import ua
from opensmi.core.frozen import FrozenMeta
from opensmi.core.ua import NodeIdDefinition


@final
class LaserSystemsNodeIds(metaclass=FrozenMeta):
    """Node identifiers from the OPC UA 'LaserSystems' nodeset. Auto-generated."""

    FILE_NAME: ClassVar[str] = "Opc.Ua.LaserSystems.NodeSet2.xml"
    URI: ClassVar[str] = "http://opcfoundation.org/UA/LaserSystems/"
    VERSION: ClassVar[str] = "1.0.0"
    REQUIRED_URIS: ClassVar[tuple[str, ...]] = (
        "http://opcfoundation.org/UA/DI/",
        "http://opcfoundation.org/UA/Machinery/",
        "http://opcfoundation.org/UA/IA/",
        "http://opcfoundation.org/UA/MachineTool/",
    )

    ActivityDataMonitoringType = NodeIdDefinition(URI, ua.Int32(1008))
    ConditionDataMonitoringType = NodeIdDefinition(URI, ua.Int32(1006))
    ConsumptionDataMonitoringType = NodeIdDefinition(URI, ua.Int32(1004))
    LaserSystemMaintenancePrognosisType = NodeIdDefinition(URI, ua.Int32(1013))
    LaserSystemMonitoringType = NodeIdDefinition(URI, ua.Int32(1002))
    LaserSystemOperationCounterType = NodeIdDefinition(URI, ua.Int32(1010))
    LaserSystemProductionType = NodeIdDefinition(URI, ua.Int32(1003))
    LaserSystemState_StateMachineType = NodeIdDefinition(URI, ua.Int32(1009))
    LaserSystemStatusType = NodeIdDefinition(URI, ua.Int32(1012))
    LaserSystemType = NodeIdDefinition(URI, ua.Int32(1005))
    LaserSystemUtilityChangePrognosisType = NodeIdDefinition(URI, ua.Int32(1014))
    RecipeSettingsAndOverviewType = NodeIdDefinition(URI, ua.Int32(1007))
