# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

# !!! autogenerated code, do not change manually !!!
# generated on 2026-09-10 09:07:06.919671+02:00

"""Node identifiers from the OPC UA 'Machinery' nodeset. Auto-generated."""

from typing import ClassVar, final

from asyncua import ua
from opensmi.core.frozen import FrozenMeta
from opensmi.core.ua import NodeIdDefinition


@final
class MachineryNodeIds(metaclass=FrozenMeta):
    """Node identifiers from the OPC UA 'Machinery' nodeset. Auto-generated."""

    FILE_NAME: ClassVar[str] = "Opc.Ua.Machinery.NodeSet2.xml"
    URI: ClassVar[str] = "http://opcfoundation.org/UA/Machinery/"
    VERSION: ClassVar[str] = "1.03.0"
    REQUIRED_URIS: ClassVar[tuple[str, ...]] = ("http://opcfoundation.org/UA/DI/",)

    IMachineTagNameplateType = NodeIdDefinition(URI, ua.Int32(1011))
    IMachineVendorNameplateType = NodeIdDefinition(URI, ua.Int32(1010))
    IMachineryItemVendorNameplateType = NodeIdDefinition(URI, ua.Int32(1003))
    MachineComponentsType = NodeIdDefinition(URI, ua.Int32(1006))
    MachineIdentificationType = NodeIdDefinition(URI, ua.Int32(1012))
    MachineryComponentIdentificationType = NodeIdDefinition(URI, ua.Int32(1005))
    MachineryItemIdentificationType = NodeIdDefinition(URI, ua.Int32(1004))
    MachineryItemState_StateMachineType = NodeIdDefinition(URI, ua.Int32(1002))
    MachineryLifetimeCounterType = NodeIdDefinition(URI, ua.Int32(1015))
    MachineryOperationCounterType = NodeIdDefinition(URI, ua.Int32(1009))
    MachineryOperationModeStateMachineType = NodeIdDefinition(URI, ua.Int32(1008))
