# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

# !!! autogenerated code, do not change manually !!!
# generated on 2026-09-10 09:07:07.043155+02:00

"""Node identifiers from the OPC UA 'MachineTool' nodeset. Auto-generated."""

from typing import ClassVar, final

from asyncua import ua
from opensmi.core.frozen import FrozenMeta
from opensmi.core.ua import NodeIdDefinition


@final
class MachineToolNodeIds(metaclass=FrozenMeta):
    """Node identifiers from the OPC UA 'MachineTool' nodeset. Auto-generated."""

    FILE_NAME: ClassVar[str] = "Opc.Ua.MachineTool.NodeSet2.xml"
    URI: ClassVar[str] = "http://opcfoundation.org/UA/MachineTool/"
    VERSION: ClassVar[str] = "1.01.1"
    REQUIRED_URIS: ClassVar[tuple[str, ...]] = (
        "http://opcfoundation.org/UA/DI/",
        "http://opcfoundation.org/UA/Machinery/",
        "http://opcfoundation.org/UA/IA/",
    )

    AlertType = NodeIdDefinition(URI, ua.Int32(39))
    BaseToolType = NodeIdDefinition(URI, ua.Int32(49))
    ChannelMode = NodeIdDefinition(URI, ua.Int32(67))
    ChannelModifierType = NodeIdDefinition(URI, ua.Int32(33))
    ChannelMonitoringType = NodeIdDefinition(URI, ua.Int32(16))
    ChannelState = NodeIdDefinition(URI, ua.Int32(64))
    ClampingConditionClassType = NodeIdDefinition(URI, ua.Int32(48))
    CombinedChannelMonitoringType = NodeIdDefinition(URI, ua.Int32(46))
    EDMGeneratorMonitoringType = NodeIdDefinition(URI, ua.Int32(42))
    EDMGeneratorState = NodeIdDefinition(URI, ua.Int32(71))
    ElementMonitoringType = NodeIdDefinition(URI, ua.Int32(23))
    EquipmentType = NodeIdDefinition(URI, ua.Int32(12))
    InterruptionConditionType = NodeIdDefinition(URI, ua.Int32(19))
    LaserMonitoringType = NodeIdDefinition(URI, ua.Int32(36))
    LaserState = NodeIdDefinition(URI, ua.Int32(70))
    MachineOperationMode = NodeIdDefinition(URI, ua.Int32(65))
    MachineOperationModeStateMachineType = NodeIdDefinition(URI, ua.Int32(1003))
    MachineOperationMonitoringType = NodeIdDefinition(URI, ua.Int32(26))
    MachineToolIdentificationType = NodeIdDefinition(URI, ua.Int32(11))
    MachineToolType = NodeIdDefinition(URI, ua.Int32(13))
    MaintenanceModeStateMachineType = NodeIdDefinition(URI, ua.Int32(1004))
    MaintenancePrognosisType = NodeIdDefinition(URI, ua.Int32(9))
    ManualActivityPrognosisType = NodeIdDefinition(URI, ua.Int32(10))
    ManualProcessStepConditionClassType = NodeIdDefinition(URI, ua.Int32(52))
    MeasurementConditionClassType = NodeIdDefinition(URI, ua.Int32(53))
    MessagesType = NodeIdDefinition(URI, ua.Int32(38))
    MonitoringType = NodeIdDefinition(URI, ua.Int32(14))
    MultiToolType = NodeIdDefinition(URI, ua.Int32(51))
    NotificationEventType = NodeIdDefinition(URI, ua.Int32(35))
    NotificationType = NodeIdDefinition(URI, ua.Int32(7))
    ObligationType = NodeIdDefinition(URI, ua.Int32(1002))
    OperatorConditionClassType = NodeIdDefinition(URI, ua.Int32(47))
    PartLoadPrognosisType = NodeIdDefinition(URI, ua.Int32(1))
    PartMissingConditionClassType = NodeIdDefinition(URI, ua.Int32(54))
    PartQuality = NodeIdDefinition(URI, ua.Int32(63))
    PartUnloadPrognosisType = NodeIdDefinition(URI, ua.Int32(5))
    ProcessChangeoverPrognosisType = NodeIdDefinition(URI, ua.Int32(8))
    ProcessIrregularity = NodeIdDefinition(URI, ua.Int32(62))
    ProcessIrregularityConditionClassType = NodeIdDefinition(URI, ua.Int32(55))
    ProductionActiveProgramType = NodeIdDefinition(URI, ua.Int32(32))
    ProductionJobEndPrognosisType = NodeIdDefinition(URI, ua.Int32(37))
    ProductionJobListType = NodeIdDefinition(URI, ua.Int32(30))
    ProductionJobStateMachineType = NodeIdDefinition(URI, ua.Int32(28))
    ProductionJobTransitionEventType = NodeIdDefinition(URI, ua.Int32(31))
    ProductionJobType = NodeIdDefinition(URI, ua.Int32(29))
    ProductionPartSetType = NodeIdDefinition(URI, ua.Int32(34))
    ProductionPartStateMachineType = NodeIdDefinition(URI, ua.Int32(40))
    ProductionPartTransitionEventType = NodeIdDefinition(URI, ua.Int32(27))
    ProductionPartType = NodeIdDefinition(URI, ua.Int32(56))
    ProductionProgramStateMachineType = NodeIdDefinition(URI, ua.Int32(15))
    ProductionProgramTransitionEventType = NodeIdDefinition(URI, ua.Int32(17))
    ProductionProgramType = NodeIdDefinition(URI, ua.Int32(59))
    ProductionStateMachineType = NodeIdDefinition(URI, ua.Int32(24))
    ProductionStatisticsType = NodeIdDefinition(URI, ua.Int32(20))
    ProductionType = NodeIdDefinition(URI, ua.Int32(21))
    PrognosisListType = NodeIdDefinition(URI, ua.Int32(2))
    PrognosisType = NodeIdDefinition(URI, ua.Int32(3))
    SoftwareIdentificationType = NodeIdDefinition(URI, ua.Int32(43))
    SpindleMonitoringType = NodeIdDefinition(URI, ua.Int32(22))
    ToolBreakageConditionClassType = NodeIdDefinition(URI, ua.Int32(57))
    ToolChangeConditionClassType = NodeIdDefinition(URI, ua.Int32(58))
    ToolChangePrognosisType = NodeIdDefinition(URI, ua.Int32(45))
    ToolLifeIndication = NodeIdDefinition(URI, ua.Int32(68))
    ToolLifeType = NodeIdDefinition(URI, ua.Int32(61))
    ToolListType = NodeIdDefinition(URI, ua.Int32(44))
    ToolLoadPrognosisType = NodeIdDefinition(URI, ua.Int32(4))
    ToolLocked = NodeIdDefinition(URI, ua.Int32(66))
    ToolManagement = NodeIdDefinition(URI, ua.Int32(69))
    ToolType = NodeIdDefinition(URI, ua.Int32(50))
    ToolUnloadPrognosisType = NodeIdDefinition(URI, ua.Int32(18))
    UtilityChangePrognosisType = NodeIdDefinition(URI, ua.Int32(6))
    UtilityConditionClassType = NodeIdDefinition(URI, ua.Int32(60))
    WorkingUnitMonitoringType = NodeIdDefinition(URI, ua.Int32(41))
