# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

# !!! autogenerated code, do not change manually !!!
# generated on 2026-09-10 09:07:07.262093+02:00

"""Node identifiers from the OPC UA 'SmartFactoryEnergyConsumptionManagement' nodeset. Auto-generated."""

from typing import ClassVar, final

from asyncua import ua
from opensmi.core.frozen import FrozenMeta
from opensmi.core.ua import NodeIdDefinition


@final
class SmartFactoryEnergyConsumptionManagementNodeIds(metaclass=FrozenMeta):
    """Node identifiers from the OPC UA 'SmartFactoryEnergyConsumptionManagement' nodeset. Auto-generated."""

    FILE_NAME: ClassVar[str] = "Opc.Ua.SmartFactory.EnergyConsumptionManagement.NodeSet2.xml"
    URI: ClassVar[str] = "http://smartfactory.de/UA/EnergyConsumptionManagement"
    VERSION: ClassVar[str] = "1.00"
    REQUIRED_URIS: ClassVar[tuple[str, ...]] = ("http://opcfoundation.org/UA/ECM/",)

    IEnergyProfileSFKL0Type = NodeIdDefinition(URI, ua.Int32(1004))
