# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

# !!! autogenerated code, do not change manually !!!
# generated on 2026-09-10 09:07:07.434938+02:00

"""Node identifiers from the OPC UA 'SmartFactorySkillSet' nodeset. Auto-generated."""

from typing import ClassVar, final

from asyncua import ua
from opensmi.core.frozen import FrozenMeta
from opensmi.core.ua import NodeIdDefinition


@final
class SmartFactorySkillSetNodeIds(metaclass=FrozenMeta):
    """Node identifiers from the OPC UA 'SmartFactorySkillSet' nodeset. Auto-generated."""

    FILE_NAME: ClassVar[str] = "Opc.Ua.SmartFactory.SkillSet.NodeSet2.xml"
    URI: ClassVar[str] = "http://smartfactory.de/UA/SkillSet"
    VERSION: ClassVar[str] = "1.00"
    REQUIRED_URIS: ClassVar[tuple[str, ...]] = ("http://opcfoundation.org/UA/DI/",)

    BaseMethodType = NodeIdDefinition(URI, ua.Int32(1004))
    BaseSkillElementType = NodeIdDefinition(URI, ua.Int32(1000))
    BaseSkillType = NodeIdDefinition(URI, ua.Int32(1001))
    CurrencyItemType = NodeIdDefinition(URI, ua.Int32(2000))
    IMetricsType = NodeIdDefinition(URI, ua.Int32(1003))
    MethodSetType = NodeIdDefinition(URI, ua.Int32(1005))
    SkillSetType = NodeIdDefinition(URI, ua.Int32(1002))
