# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

# !!! autogenerated code, do not change manually !!!
# generated on 2026-09-10 09:07:07.337553+02:00

"""Node identifiers from the OPC UA 'SmartFactoryMachineSet' nodeset. Auto-generated."""

from typing import ClassVar, final

from asyncua import ua
from opensmi.core.frozen import FrozenMeta
from opensmi.core.ua import NodeIdDefinition


@final
class SmartFactoryMachineSetNodeIds(metaclass=FrozenMeta):
    """Node identifiers from the OPC UA 'SmartFactoryMachineSet' nodeset. Auto-generated."""

    FILE_NAME: ClassVar[str] = "Opc.Ua.SmartFactory.MachineSet.NodeSet2.xml"
    URI: ClassVar[str] = "http://smartfactory.de/UA/MachineSet"
    VERSION: ClassVar[str] = "1.00"
    REQUIRED_URIS: ClassVar[tuple[str, ...]] = (
        "http://opcfoundation.org/UA/DI/",
        "http://opcfoundation.org/UA/RSL/",
        "http://opcfoundation.org/UA/Machinery/",
        "http://smartfactory.de/UA/SkillSet",
    )

    AlertType = NodeIdDefinition(URI, ua.Int32(1001))
    AssetType = NodeIdDefinition(URI, ua.Int32(1002))
    CartesianWorkspace = NodeIdDefinition(URI, ua.Int32(3003))
    CartesianWorkspaceType = NodeIdDefinition(URI, ua.Int32(2001))
    ComponentType = NodeIdDefinition(URI, ua.Int32(1008))
    ContinuousSkillType = NodeIdDefinition(URI, ua.Int32(1016))
    CylindricalWorkspace = NodeIdDefinition(URI, ua.Int32(3004))
    CylindricalWorkspaceType = NodeIdDefinition(URI, ua.Int32(2002))
    FiniteSkillType = NodeIdDefinition(URI, ua.Int32(1015))
    MachineType = NodeIdDefinition(URI, ua.Int32(1009))
    MachineryItemType = NodeIdDefinition(URI, ua.Int32(1007))
    MonitoringType = NodeIdDefinition(URI, ua.Int32(1006))
    NotificationType = NodeIdDefinition(URI, ua.Int32(1003))
    ResourceItemIdentificationType = NodeIdDefinition(URI, ua.Int32(1004))
    ResourceType = NodeIdDefinition(URI, ua.Int32(1011))
    ResourcesType = NodeIdDefinition(URI, ua.Int32(1005))
    SkillElementType = NodeIdDefinition(URI, ua.Int32(1013))
    SkillStateMachineType = NodeIdDefinition(URI, ua.Int32(1014))
    UserType = NodeIdDefinition(URI, ua.Int32(1023))
    UsersType = NodeIdDefinition(URI, ua.Int32(1024))
    Workspace = NodeIdDefinition(URI, ua.Int32(3000))
    WorkspaceType = NodeIdDefinition(URI, ua.Int32(2000))
