# SPDX-FileCopyrightText: 2026 OpenSMI Contributors
#
# SPDX-License-Identifier: MIT

import re
import subprocess
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from pprint import pformat
from string import Template
from typing import Final

from asyncua.ua import NodeId

# NODESET_PATH: Final[Path] = Path("../src/opensmi/server/nodesets")
# OUTPUT_PATH: Final[Path] = Path("../src/opensmi/server/nodesets")
TYPE_TAGS: Final[set[str]] = {"UAObjectType", "UADataType", "UAVariableType"}
TEMPLATE: Final[Template] = Template(Path("nodeset.py.template").read_text(encoding="utf-8"))


def _snake_case(value: str) -> str:
    value = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", value)
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    return value.lower()


@dataclass
class _ModelEntry:
    uri: str
    publication_date: str
    version: str


@dataclass
class _ParsedNodeSet:
    name: str
    path: Path
    model: _ModelEntry
    required_models: list[_ModelEntry]
    entries: dict[str, int]


@dataclass
class _ProcessModelEntry(_ModelEntry):
    path: Path
    class_name: str


def _write(parsed: _ParsedNodeSet) -> tuple[str, Path]:
    class_name = f"{parsed.name}NodeIds"
    required_uris = [
        model.uri
        for model in parsed.required_models
        if model.uri not in (parsed.model.uri, "http://opcfoundation.org/UA/")
    ]

    identifier_source = "\n".join(
        f"    {entry} = NodeIdDefinition(URI, ua.Int32({parsed.entries[entry]!r}))" for entry in sorted(parsed.entries)
    )

    path = Path(f"{_snake_case(parsed.name)}.py")
    with path.open("w") as file:
        file.write(
            TEMPLATE.substitute(
                generated_on=datetime.now().astimezone(),
                class_name=class_name,
                nodeset=parsed.name,
                file_name=parsed.path.name,
                uri=parsed.model.uri,
                version=parsed.model.version,
                required_uris=pformat(tuple(required_uris)),
                identifiers=identifier_source,
            )
        )

    return class_name, path


def _write__init__(files: list[_ProcessModelEntry]) -> None:
    path = Path(".") / "__init__.py"
    with path.open("w") as file:
        file.write("# SPDX-FileCopyrightText: 2026 OpenSMI Contributors\n")
        file.write("#\n")
        file.write("# SPDX-License-Identifier: MIT\n\n")
        file.write("# !!! autogenerated code, do not change manually !!!\n")
        file.write(f"# generated on {datetime.now().astimezone()}\n\n")
        file.write('"""Autogenerated OPC UA node identifiers."""\n\n')
        file.write("from typing import Final\n\n")
        file.write("from opensmi.core.protocols import NamespaceProvider\n\n")

        for entry in files:
            file.write(f"from .{entry.path.stem} import {entry.class_name} as {entry.class_name}\n")

        file.write("\n\n")
        file.write("NODE_SETS: Final[dict[str, type[NamespaceProvider]]] = {\n")
        for entry in files:
            file.write(f'    "{entry.uri}": {entry.class_name},\n')
        file.write("}\n")

    _check(path)


def _check(path: Path) -> None:
    subprocess.run(["ruff", "check", "--fix", str(path)], check=True)
    subprocess.run(["ruff", "format", str(path)], check=True)

    with open(path, encoding="utf-8") as f:
        generated_code = f.read()

    # finally, make sure the file is valid python after formatting & linting
    compile(generated_code, path, "exec")


def _process_model(node: ET.Element) -> _ModelEntry:
    model_uri = node.attrib.get("ModelUri")
    assert model_uri

    return _ModelEntry(
        uri=model_uri,
        publication_date=node.attrib.get("PublicationDate", "??"),
        version=node.attrib.get("Version", "??"),
    )


def _process_models(node: ET.Element) -> tuple[_ModelEntry, list[_ModelEntry]]:
    model = _process_model(node)
    required_models = [_process_model(child) for child in node.iter()]
    return model, required_models


def _parse_nodeset_xml(path: Path) -> _ParsedNodeSet:
    print(f"INFO: Processing '{path}'...")
    entries: dict[str, int] = {}

    tree = ET.parse(path)
    root = tree.getroot()

    uri, required_models = None, None
    for node in root.iter():  # Iterate through all UAObjectType nodes
        local_name = node.tag.rsplit("}", 1)[-1]  # without xml namespace

        if local_name == "Model":
            # TODO(CaHa): what about multiple "model" tags?
            uri, required_models = _process_models(node)
            continue
        if local_name not in TYPE_TAGS:
            continue
        try:
            bname = node.attrib.get("BrowseName")
            assert bname
            name = bname.split(":")[-1]
            raw_node_id = node.attrib.get("NodeId")
            assert raw_node_id
            node_id = NodeId.from_string(raw_node_id)

            if name in entries:
                print(f"WARNING: '{name}' already used, skipping!")
                continue
            entries[name] = int(node_id.Identifier)
        except (ValueError, AttributeError):
            print(f"WARNING: Could not process {node}, skipping!")

    if uri is None:
        print(f"ERROR: No URI found in {path}, aborting!")
        exit(1)

    # fail if these don't exist
    assert uri
    assert required_models

    return _ParsedNodeSet(
        name="".join(path.stem.split(".")[2:-1]),
        path=path,
        model=uri,
        required_models=required_models,
        entries=entries,
    )


def main() -> None:  # noqa: D103
    files = []
    for src_path in Path(".").glob("*.NodeSet2.xml"):
        parsed = _parse_nodeset_xml(src_path)
        class_name, dest_path = _write(parsed)
        files.append(
            _ProcessModelEntry(
                uri=parsed.model.uri,
                publication_date=parsed.model.publication_date,
                version=parsed.model.version,
                path=dest_path,
                class_name=class_name,
            )
        )

        # format and lint generated file, check for errors
        _check(dest_path)

    _write__init__(files)


if __name__ == "__main__":
    main()
