# SPDX-FileCopyrightText: 2026 The Authors
#
# SPDX-License-Identifier: MIT

import logging
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import IO

from openpyxl import load_workbook

logging.basicConfig(level=logging.INFO)
_LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True)
class _UneceUnit:
    name: str
    symbol: str
    common_code: str
    level: str


def _common_code_to_ua_unit_id(common_code: str) -> int:
    """Calculate the unit ID for OPC UA.

    Conversion algorithm from https://reference.opcfoundation.org/specs/OPC-10000-8/5.6.4.4
    """
    result: int = 0
    for char in common_code:
        result = (result << 8) | ord(char)
    return result


def _sanitize(value: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9_]", "_", value)
    value = value.replace("_x000D_", "_")  # excel ??
    value = re.sub(r"_+", "_", value)
    value = value.strip("_")
    if value[0].isdigit():
        value = f"UNIT_{value}"
    return value.upper()


def _write_header(io: IO, class_name: str, doc: str) -> None:
    io.write('"""SI Units as type-checkable enum."""\n\n')
    io.write("# !!! autogenerated code, do not change manually !!!\n")
    io.write(f"# generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")  # noqa: DTZ005
    io.write("from open_smi.common.unit_base import BaseUnit\n\n\n")
    io.write(f"class {class_name}(BaseUnit):\n")
    io.write(f'    """{doc} as a type-checkable enum. Generated from UN/CEFACT-Rec20.\n\n')
    io.write("    See https://unece.org/trade/documents/2021/06/uncefact-rec20-0\n")
    io.write('    """\n\n')


def _write_unit(io: IO, unit: _UneceUnit) -> None:
    symbol = unit.symbol.split(" or ")  # there are multiple display names separated by " or "
    io.write(f"    {unit.name} = ({symbol[-1]!r}, {_common_code_to_ua_unit_id(unit.common_code)})\n")


def _parse(path: Path) -> dict[str, _UneceUnit]:
    units: dict[str, _UneceUnit] = {}

    workbook = load_workbook(path, read_only=True, data_only=True)
    for worksheet in (workbook["Annex I"], workbook["Annex II & Annex III"]):
        rows = worksheet.iter_rows(values_only=True)
        header = next(rows)
        # map name to index
        column = {_sanitize(str(name)): index for index, name in enumerate(header) if name is not None}

        for row in rows:
            name = row[column["NAME"]]
            if not name:
                _LOGGER.warning(f"Skipping row, no name {row=}!")
                continue
            name = _sanitize(str(name))

            symbol = row[column["SYMBOL"]]
            if not symbol:
                _LOGGER.warning(f"no symbol, using name as symbol {row=}!")
                # continue
                symbol = str(row[column["NAME"]])

            if symbol == "grade":
                _LOGGER.warning(f"Skipping symbol={symbol=} because it's common code is ambiguous with symbol 'gon'!")
                continue

            common_code = row[column["COMMON_CODE"]]
            if not common_code:
                _LOGGER.warning(f"Skipping row, no common code {row=}!")
                continue

            level = row[column["LEVEL_CATEGORY"]]
            if not level:
                _LOGGER.warning(f"Skipping row, no level {row=}!")
                continue

            unit = _UneceUnit(
                name=name,
                symbol=str(symbol),
                common_code=str(common_code),
                level=str(level),
            )

            if name not in units:
                units[name] = unit
            elif units[name] != unit:
                _LOGGER.warning(f"Duplicate name {name=}! existing:{units[name]=} new:{unit}")

    workbook.close()
    return units


def _write_python_file(path: Path, units: dict[str, _UneceUnit], class_name: str, doc: str) -> None:
    with path.open("w", encoding="utf-8") as file:
        _write_header(file, class_name=class_name, doc=doc)
        for unit in sorted(units.values(), key=lambda x: x.name):
            _write_unit(file, unit)
    _LOGGER.info(f"Written {class_name=} {doc=} to {path=}")


def _main() -> None:
    units = _parse(Path("rec20_Rev17e-2021_0.xlsx"))

    # si_units = {k: v for k, v in units.items() if "1" in v.level}
    # _write_python_file(
    #     Path("../open_smi/common/unit_si.py"), units=si_units, class_name="SiUnit", doc="SI normative units"
    # )
    #
    # si_equivalent_units = {k: v for k, v in units.items() if "2" in v.level}
    # _write_python_file(
    #     Path("../open_smi/common/unit_si_equivalent.py"),
    #     units=si_equivalent_units,
    #     class_name="SiEquivalentUnit",
    #     doc="SI normative equivalent units",
    # )
    #
    # informative_units = {k: v for k, v in units.items() if "3" in v.level}
    # _write_python_file(
    #     Path("../open_smi/common/unit_informative.py"),
    #     units=informative_units,
    #     class_name="InformativeUnit",
    #     doc="Informative units",
    # )

    _write_python_file(Path("../src/open_smi_common/unit_all.py"), units=units, class_name="Unit", doc="All units")


if __name__ == "__main__":
    _main()
